[package]
name = "sdkman-cli-native"
version = "0.0.19"
edition = "2021"
publish = false

[dependencies]
assert_cmd = "2.0.8"
proc-macro2 = "1.0.50"
clap = { version = "4.1.4", features = ["derive"] }
colored = "2.0.0"
dirs = "4.0.0"
exitcode = "1.1.2"
home = "0.5.4"
predicates = "2.1.5"
serial_test = "1.0.0"
tempfile = "3.3.0"
textwrap = "0.16.0"
