[package]
name = "sdkman-cli-native"
version = "0.6.0"
edition = "2021"
publish = false

[dependencies]
assert_cmd = "2.0.16"
proc-macro2 = "1.0.94"
clap = { version = "4.5.31", features = ["derive"] }
colored = "3.0.0"
directories = "5.0.0"
dirs = "5.0.1"
exitcode = "1.1.2"
fs_extra = "1.3.0"
predicates = "3.1.3"
serial_test = "3.2.0"
symlink = "0.1.0"
tempfile = "3.18.0"
textwrap = "0.16.2"
