[package]
name = "sdkman-cli-native"
version = "0.2.2"
edition = "2021"
publish = false

[dependencies]
assert_cmd = "2.0.10"
proc-macro2 = "1.0.56"
clap = { version = "4.2.5", features = ["derive"] }
colored = "2.0.0"
dirs = "5.0.0"
exitcode = "1.1.2"
home = "0.5.4"
predicates = "3.0.3"
serial_test = "2.0.0"
symlink = "0.1.0"
tempfile = "3.5.0"
textwrap = "0.16.0"
