[package]
name = "sdkman-cli-native"
version = "0.3.2"
edition = "2021"
publish = false

[dependencies]
assert_cmd = "2.0.12"
proc-macro2 = "1.0.66"
clap = { version = "4.3.17", features = ["derive"] }
colored = "2.0.4"
directories = "5.0.0"
dirs = "5.0.1"
exitcode = "1.1.2"
fs_extra = "1.3.0"
predicates = "3.0.3"
serial_test = "2.0.0"
symlink = "0.1.0"
tempfile = "3.7.0"
textwrap = "0.16.0"
