[package]
name = "sdkman-cli-native"
version = "0.4.6"
edition = "2021"
publish = false

[dependencies]
assert_cmd = "2.0.13"
proc-macro2 = "1.0.78"
clap = { version = "4.5.1", features = ["derive"] }
colored = "2.1.0"
directories = "5.0.0"
dirs = "5.0.1"
exitcode = "1.1.2"
fs_extra = "1.3.0"
predicates = "3.1.0"
serial_test = "3.0.0"
symlink = "0.1.0"
tempfile = "3.10.1"
textwrap = "0.16.0"
