[package]
name = "sdkman-cli-native"
version = "0.0.15"
edition = "2021"
publish = false

[dependencies]
assert_cmd = "2.0.4"
clap = "4.0.2"
colored = "2.0.0"
dirs = "4.0.0"
exitcode = "1.1.2"
predicates = "2.1.2"
serial_test = "0.9.0"
tempfile = "3.3.0"
textwrap = "0.15.1"
